### PR TITLE
Ensure ssh and scp works as expected with password 

### LINKED ISSUE #47: Ensure ssh and scp works as expected with password
**Describe the bug**
SSH and SCP does not accept passwords as parameters. Ensure commands used with ssh and scp works as expected with password.

### PR DESCRIPTION
**Pull request by aprajshekhar**
Fixes #47 

## Proposed Changes

  - Password provided via sshpass
  - More logs
  - updated commands to work with sshpass

### CODE REVIEW

File: deploy.sh [hunk 1]
```diff
@@ -7,8 +7,8 @@ REMOTE_JAR_FILE=gamedoora-user-services.jar
 echo $SSH_USERNAME
 echo $SSH_HOST
 
-# connect to the Server instance and set up the remote directory
-ssh -o StrictHostKeyChecking=no "$SSH_USERNAME:$SSH_PASSWORD@$SSH_HOST" "
+# connect to the Server instance and set up the remote directory 
+ sshpass -p $SSH_PASS ssh -o StrictHostKeyChecking=no "$SSH_USERNAME@$SSH_HOST" "
```
Comment (picksitquick) [inline deploy.sh:11]: Okay so the command to use password was sshpass instead of ssh.

File: deploy.sh [hunk 2]
```diff
@@ -20,18 +20,29 @@ ssh -o StrictHostKeyChecking=no "$SSH_USERNAME:$SSH_PASSWORD@$SSH_HOST" "
 
 #COPY SYSTEMD INTO LOCAL
 DEST_PATH="/usr/lib/systemd/system/"
-scp gamedoora-user-service.service -o StrictHostKeyChecking=no "$SSH_USERNAME:$SSH_PASSWORD@$SSH_HOST:$DEST_PATH"
-
+echo "=====Copying files========="
```
Comment (picksitquick) [inline deploy.sh:23]: Thanks for adding echo commands, it will make more readable at the host.

**Review by picksitquick — APPROVED** [review]
